## Train the First Model

In [5]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [6]:
training_data = pd.read_csv("../data/processed/training_data.csv")

training_data.head()

,home_avg_goals,away_avg_goals,home_avg_goals_against,away_avg_goals_against,home_win_rate,away_win_rate,home_goal_difference,away_goal_difference,home_career_matches,away_career_matches,neutral,target
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,1
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,1,0,2
2,1.000000,2.000000,2.000000,1.000000,0.000000,0.500000,-1.000000,1.000000,2,2,0,2
3,1.666667,1.333333,1.333333,1.666667,0.333333,0.333333,0.333333,-0.333333,3,3,0,1
4,1.500000,1.750000,1.750000,1.500000,0.250000,0.250000,-0.250000,0.250000,4,4,0,2

### Create X and y

#### Features:

In [7]:
X = training_data.drop(columns=["target"])

#### Target:

In [8]:
y = training_data["target"]

In [9]:
X.head()

,home_avg_goals,away_avg_goals,home_avg_goals_against,away_avg_goals_against,home_win_rate,away_win_rate,home_goal_difference,away_goal_difference,home_career_matches,away_career_matches,neutral
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,1,0
2,1.000000,2.000000,2.000000,1.000000,0.000000,0.500000,-1.000000,1.000000,2,2,0
3,1.666667,1.333333,1.333333,1.666667,0.333333,0.333333,0.333333,-0.333333,3,3,0
4,1.500000,1.750000,1.750000,1.500000,0.250000,0.250000,-0.250000,0.250000,4,4,0

In [10]:
y.head()

0    1
1    2
2    2
3    1
4    2
Name: target, dtype: int64

### Split the data

In [11]:
split_index = int(len(training_data) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

#### Now:
#### First 80% → Training
#### Last 20% → Testing

## Train the model

In [12]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

## Make predictions

In [13]:
predictions = model.predict(X_test)

## Accuracy

In [14]:
accuracy = accuracy_score(y_test, predictions)

print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.5655

## Classification report

In [15]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.53      0.54      0.53      2881
           1       0.29      0.00      0.01      2311
           2       0.58      0.86      0.69      4736

    accuracy                           0.57      9928
   macro avg       0.47      0.47      0.41      9928
weighted avg       0.50      0.57      0.49      9928

## Confusion matrix

In [16]:
cm = confusion_matrix(y_test, predictions)

print(cm)

[[1557    4 1320]
 [ 716    6 1589]
 [ 674   11 4051]]